version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper-container
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      project3-network:
        ipv4_address: 172.25.0.7
  # KAFKA
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka-container
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami"
    networks:
      project3-network:
        ipv4_address: 172.25.0.8
    depends_on:
      - zookeeper

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  project3-network:
    #    name: project3-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
#          gateway: 172.25.0.1